### ISSUE TITLE
Gzip not working on Circle CI

### ISSUE THREAD

**Issue by evemontalvao** [pahuta/gzip-cli#40]
Hey, I'm having some problem using gzip. It works perfectly locally, but when I try to run in the CI pipeline I get the following error:

```
$ yarn secrets:install
yarn run v1.22.11
$ curl -sSL https://github.com/OmnipresentGroup/secrets/raw/main/install.sh | sh
**gzip-cli: no one pattern is specified. Operation is skipped.mv**: cannot stat 'secrets-main': No such file or directory
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```
I'm using node 14.17.
Am I missing something? 'Cause this error seems to happen when the package is being installed.

Thank you in advance

**Comment by pahuta** [comment]
@Hi, @evemontalvao.
According to the error message, the glob pattern was not specified. Pattern(s) is a required parameter to take `gzip-cli` know which files to compress.

Check the executed command, it should be something like `gzip dist/**/*.js`.

**Comment by evemontalvao** [comment]
Hey @pahuta, sorry I forgot to put this in the example, but this is the command I'm running:
`gzip build/static/js/*.js && gzip build/static/css/*.css`

Locally, it works like a charm, but on Circle CI I get the error above before running the command, this error happens when the package is being installed

**Comment by pahuta** [comment]
@evemontalvao , try to wrap patterns into double quotes:
```bash
gzip \"build/static/js/*.js\" && gzip \"build/static/css/*.css\"
```

[Source](https://goulet.dev/posts/quotes-around-globs/)

**Comment by pahuta** [comment]
Closed due to inactivity.
